version: "2.0"

endpoints:
  metal_endpoint:
    kind: ip

services:
  metal-blockchain:
    image: ubuntu:22.04
    command:
      - /bin/bash
      - -c
      - |
        echo 'Installing MetalGo on Ubuntu for MAINNET...'
        apt-get update -o Acquire::http::Pipeline-Depth=0
        apt-get install -y --no-install-recommends wget curl jq ca-certificates
        
        echo 'Downloading MetalGo v1.12.0-hotfix...'
        wget --no-check-certificate -O metalgo.tar.gz \
          https://github.com/MetalBlockchain/metalgo/releases/download/v1.12.0-hotfix/metalgo-linux-amd64-v1.12.0-hotfix.tar.gz
        
        echo 'Extracting MetalGo...'
        tar -xzf metalgo.tar.gz
        mv metalgo-v1.12.0-hotfix/metalgo /usr/local/bin/
        chmod +x /usr/local/bin/metalgo
        rm -rf metalgo-v1.12.0-hotfix metalgo.tar.gz
        
        echo 'Creating data directory...'
        mkdir -p /root/.metalgo
        
        echo 'Setting file descriptor limits...'
        ulimit -n 65536
        echo "File descriptor limit set to: $(ulimit -n)"
        
        echo '========================================='
        echo 'Starting MetalGo node on MAINNET'
        echo 'Attempting to detect MetalLB LoadBalancer IP...'
        echo '========================================='
        
        # Try to get the LoadBalancer IP from Kubernetes API
        # This requires the service account token to be mounted
        PUBLIC_IP=""
        
        # Method 1: Query Kubernetes API for service LoadBalancer IP
        if [ -f /var/run/secrets/kubernetes.io/serviceaccount/token ]; then
          echo "Kubernetes service account found, querying API..."
          K8S_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
          K8S_API="https://kubernetes.default.svc"
          NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace 2>/dev/null || echo "default")
          
          # Query for metal-blockchain service LoadBalancer IP
          LB_IP=$(curl -s -k -H "Authorization: Bearer $K8S_TOKEN" \
            "$K8S_API/api/v1/namespaces/$NAMESPACE/services/metal-blockchain" 2>/dev/null | \
            jq -r '.status.loadBalancer.ingress[0].ip // empty' 2>/dev/null)
          
          if [ -n "$LB_IP" ] && [[ "$LB_IP" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            PUBLIC_IP="$LB_IP"
            echo "Detected LoadBalancer IP from Kubernetes API: $PUBLIC_IP"
          fi
        fi
        
        # Start MetalGo
        if [ -n "$PUBLIC_IP" ]; then
          echo "Starting MetalGo with detected IP: $PUBLIC_IP"
          /usr/local/bin/metalgo \
            --network-id=mainnet \
            --http-host=0.0.0.0 \
            --http-port=9650 \
            --staking-port=9651 \
            --staking-host=0.0.0.0 \
            --public-ip=$PUBLIC_IP \
            --log-level=info &
        else
          echo "Could not detect LoadBalancer IP - starting without --public-ip"
          echo "MetalGo will use NAT traversal to discover public IP"
          /usr/local/bin/metalgo \
            --network-id=mainnet \
            --http-host=0.0.0.0 \
            --http-port=9650 \
            --staking-port=9651 \
            --staking-host=0.0.0.0 \
            --log-level=info &
        fi
        
        METAL_PID=$!
        
        echo 'Waiting for MetalGo to initialize (30 seconds)...'
        sleep 30
        
        echo 'Waiting for API to be ready...'
        for i in {1..20}; do
          if curl -s --max-time 5 http://localhost:9650/ext/health > /dev/null 2>&1; then
            echo 'API is ready!'
            break
          fi
          echo "Waiting for API... attempt $i/20"
          sleep 15
        done
        
        echo 'Waiting for blockchain to bootstrap...'
        while true; do
          RESPONSE=$(curl -s --max-time 10 -X POST \
            -H 'Content-Type: application/json' \
            -d '{"jsonrpc":"2.0","method":"info.isBootstrapped","params":{"chain":"X"},"id":1}' \
            http://localhost:9650/ext/info 2>/dev/null)
          
          if echo "$RESPONSE" | jq -e '.result.isBootstrapped == true' > /dev/null 2>&1; then
            echo 'Bootstrap complete!'
            break
          fi
          echo 'Still bootstrapping... (this can take several minutes)'
          sleep 30
        done
        
        # Wait a bit more for P2P connections to establish
        echo 'Waiting for P2P connections to establish...'
        sleep 15
        
        # Get node information
        echo 'Retrieving node information...'
        NODE_INFO=$(curl -s -X POST -H 'Content-Type: application/json' \
          -d '{"jsonrpc":"2.0","method":"info.getNodeID","params":{},"id":1}' \
          http://localhost:9650/ext/info 2>/dev/null)
        
        NODE_ID=$(echo "$NODE_INFO" | jq -r '.result.nodeID // "N/A"' 2>/dev/null)
        BLS_KEY=$(echo "$NODE_INFO" | jq -r '.result.nodePOP.publicKey // "N/A"' 2>/dev/null)
        BLS_SIG=$(echo "$NODE_INFO" | jq -r '.result.nodePOP.proofOfPossession // "N/A"' 2>/dev/null)
        
        # Get peer information
        PEERS_INFO=$(curl -s -X POST -H 'Content-Type: application/json' \
          -d '{"jsonrpc":"2.0","method":"info.peers","params":{},"id":1}' \
          http://localhost:9650/ext/info 2>/dev/null)
        
        PEER_COUNT=$(echo "$PEERS_INFO" | jq -r '.result.numPeers // 0' 2>/dev/null)
        if [ -z "$PEER_COUNT" ] || [ "$PEER_COUNT" = "null" ]; then
          PEER_COUNT=0
        fi
        
        # Get the public IP we passed to MetalGo (if any)
        if [ -n "$PUBLIC_IP" ] && [[ "$PUBLIC_IP" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          ADVERTISED_IP="$PUBLIC_IP (from Kubernetes API)"
        else
          # Try to get it from MetalGo's info API
          NODE_IP_INFO=$(curl -s -X POST -H 'Content-Type: application/json' \
            -d '{"jsonrpc":"2.0","method":"info.getNodeIP","params":{},"id":1}' \
            http://localhost:9650/ext/info 2>/dev/null)
          DETECTED_IP=$(echo "$NODE_IP_INFO" | jq -r '.result.ip // empty' 2>/dev/null)
          if [ -n "$DETECTED_IP" ]; then
            ADVERTISED_IP="$DETECTED_IP (auto-discovered by MetalGo)"
          else
            ADVERTISED_IP="Check Akash Console for actual IP"
          fi
        fi
        
        echo ""
        echo "========================================"
        echo "=== METAL MAINNET VALIDATOR SETUP DATA ==="
        echo "========================================"
        echo ""
        echo "Copy the following data to your Metal MAINNET dashboard:"
        echo ""
        echo "Node ID:"
        echo "$NODE_ID"
        echo ""
        echo "BLS Public Key:"
        echo "$BLS_KEY"
        echo ""
        echo "BLS Signature (Proof of Possession):"
        echo "$BLS_SIG"
        echo ""
        echo "========================================"
        echo "=== NETWORK STATUS ==="
        echo "========================================"
        echo ""
        echo "Public IP: $ADVERTISED_IP"
        echo "Connected Peers: $PEER_COUNT"
        echo "Network: Metal Mainnet"
        echo "RPC Endpoint: http://<your-deployment-url>:9650"
        echo "P2P Port: 9651"
        echo ""
        echo "Explorer: https://metalscan.io/"
        echo "Search for your Node ID in the explorer to verify connectivity"
        echo ""
        echo "========================================"
        echo "=== MAINNET DEPLOYMENT COMPLETE ==="
        echo "========================================"
        echo ""
        
        if [ "$PEER_COUNT" -gt 0 ] 2>/dev/null; then
          echo "✅ SUCCESS: Node is connected to $PEER_COUNT peer(s)"
          echo "✅ Your node should appear as 'Connected' in the explorer"
        else
          echo "⚠️  WARNING: Node has 0 peers (may still be connecting)"
          echo "⚠️  Wait 5-10 minutes and check the explorer"
        fi
        
        echo ""
        echo "Keeping node running... (check logs for ongoing activity)"
        
        # Keep container running and show periodic status
        while true; do
          sleep 300  # Every 5 minutes
          CURRENT_PEERS=$(curl -s -X POST -H 'Content-Type: application/json' \
            -d '{"jsonrpc":"2.0","method":"info.peers","params":{},"id":1}' \
            http://localhost:9650/ext/info | jq -r '.result.numPeers // 0')
          echo "[$(date)] Status: Connected to $CURRENT_PEERS peer(s)"
        done
    
    expose:
      - port: 9650
        as: 9650
        to:
          - global: true
            ip: metal_endpoint
        proto: tcp
      - port: 9651  
        as: 9651
        to:
          - global: true
            ip: metal_endpoint
        proto: tcp

profiles:
  compute:
    metal-blockchain:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 4Gi
        storage:
          - size: 120Gi

  placement:
    akash-providers:
      attributes:
        host: akash
        ip-lease: true
      pricing:
        metal-blockchain:
          denom: uakt
          amount: 3000

deployment:
  metal-blockchain:
    akash-providers:
      profile: metal-blockchain
      count: 1
